//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourism_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demo
    {
        public int Id { get; set; }
        public string row { get; set; }
        public string col { get; set; }
        public string data { get; set; }
        public string colors { get; set; }
    }
    public class ScheduleSaveFormat
    {
        public string row { get; set; }
        public string col { get; set; }
        public string colors { get; set; }
    }
}
